Repository FRONTENDBOOTCAMP-13th/JS-10-Coding-Dreamtree-Training-Center, pull requests merged in 2025-05, with the labels that each got.

#2 🎉 Init: 프로젝트 초기 생성 및 환경 설정
  eslint.config.js
  index.html
  package-lock.json
  package.json
  prettier.config.js
  src/components/.gitkeep
  src/components/Sample/sample.html
  src/counter.ts
  src/main.ts
  src/pages/.gitkeep
  src/pages/sample.html
  src/pages/sample.ts
  src/style.css
  src/typescript.svg
  vite.config.js
Labels: ⚙️ Setting, ✅ Done

#9 Hyunsoo PR 테스트
  testHyunsoo.js
Labels: 🧪 Test, ✅ Done

#7 PR 테스트 완료했습니다.
  test-youngjune.js
Labels: 🧪 Test, ✅ Done

#10 ✅ Test: 초기 설정용 테스트 코드 추가
  src/pages/test.html
Labels: 🧪 Test

#18 ✨ feat: Sidebar 컴포넌트 1차 구현
  src/components/Sidebar/sidebar.html
Labels: ✨ Feature, 🎨 Html&css

#19 ✨ Feat: 버튼 컴포넌트 UI 제작
  index.html
  src/assets/arrow-to-bottom.svg
  src/assets/eliminate.svg
  src/assets/external-link.svg
  src/assets/plus.svg
  src/components/Button/button.html
Labels: 🎨 Html&css, ✅ Done

#20 💄 style: Sidebar 컴포넌트 수정
  index.html
  public/img/arrow-to-bottom.svg
  public/img/bookmark-active.svg
  public/img/bookmark.svg
  public/img/compass-active.svg
  public/img/compass.svg
  public/img/dashboard-active.svg
  public/img/dashboard.svg
  public/img/eliminate.svg
  public/img/external-link.svg
  public/img/plus.svg
  public/img/settings-active.svg
  public/img/settings.svg
  src/components/Sidebar/Sidebar.ts
  src/components/Sidebar/sidebar.html
Labels: ✨ Feature, 🎨 Html&css

#21 ✨ Feat: 리소스 카드 컴포넌트 제작
  index.html
  public/img/category.svg
  public/img/difficulty.svg
  src/components/ResourceCard/resource-card.html
  src/pages/bookmark.html
  src/pages/dashboard.html
  src/pages/resource.html
Labels: 🎨 Html&css, ✅ Done

#25 ✨feat: GitHub 카드 컴포넌트 추가
  .gitignore
  index.html
  package-lock.json
  package.json
  src/api/githubApi.ts
  src/components/GithubCard/GithubCard.ts
  src/components/GithubCard/github-card.html
  src/data/colors.json
  src/types/github.type.ts
Labels: ✨ Feature, ✅ Done

#23 ✨ feat: Resource Page UI 테스트용 (header 추가 필요)
  index.html
  src/components/ResourceCard/resource-card.html
  src/components/Sample/sample.html
  src/pages/resource.html
Labels: 🎨 Html&css

#31 ✨ feat: 개발 리소스 데이터 JSON 파일 추가
  src/data/resource.json
Labels: ✨ Feature

#28 ✨ feat: Sidebar 페이지 이동 기능 추가
  src/components/Sidebar/Sidebar.ts
  src/components/Sidebar/sidebar.html
  src/pages/resource.html
Labels: ✨ Feature

#33 ♻️ refactor : resource-card 컴포넌트 수정 및 resource 페이지 마크업 수정
  src/components/ResourceCard/resource-card.html
  src/pages/resource.html
Labels: 🔨 Refactor, 🎨 Html&css, ✅ Done

#35 💄 style: resource UI 수정
  src/pages/resource.html
Labels: 🔨 Refactor, 🎨 Html&css, ✅ Done

#36 ✨ feat: Footer 컴포넌트 구현
  index.html
  public/img/figma-logo.svg
  public/img/github-mark.svg
  public/img/info-circle.svg
  src/components/Footer/footer.html
Labels: 🎨 Html&css, ✅ Done

#37 💄style: bookmark page UI 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  src/components/Button/button.html
  src/data/colors.json
  src/pages/bookmark.html
  src/style.css
Labels: 🎨 Html&css, ✅ Done

#42 Feature/resource/youngjune
  index.html
  public/img/close.svg
  public/img/share.svg
  src/components/Modal/modal.html
  src/main.ts
  src/pages/resource.html
  src/script/modalRendering.ts
  src/script/resourceRendering.ts
  src/types/type.ts
Labels: ✨ Feature, 🎨 Html&css, ✅ Done

#46 ✨ feat: 카테고리 필터링 기능 추가
  src/pages/resource.html
  src/script/filter.ts
  src/types/filter.type.ts
Labels: ✨ Feature

#47 🐛 bugfix: filter, resourceRendering 파일 충돌 이슈 해결
  src/pages/resource.html
  src/script/filter.ts
  src/script/resourceRendering.ts
Labels: 🐞 BugFix, 🔨 Refactor, ✅ Done

#49 ✨ feat: DailyResources 컴포넌트 구현
  index.html
  src/components/DailyResources/daily-resources.html
  src/components/DailyResources/daily-resources.ts
  src/main.ts
Labels: ✨ Feature, ✅ Done

#50 💫 merge: feature/dashboard/hyunsoo 브랜치 변경사항 develop 브랜치에 병합
  src/api/githubApi.ts
  src/components/GithubCard/GithubCard.ts
  src/main.ts
  src/pages/dashboard.html
  src/script/dailyResources.ts
  src/script/resourceRendering.ts
  src/style.css
Labels: ✨ Feature, 🎨 Html&css, ✅ Done

#55 ✨feat: 언어 필터 기능 추가
  src/data/resource.json
  src/script/filter.ts
  src/types/filter.type.ts
  src/types/type.ts
Labels: ✨ Feature

#57 🐛 bugfix: DailyResources compile 오류 해결과 모달 연결
  src/components/DailyResources/daily-resources.html
  src/components/DailyResources/daily-resources.ts
  src/pages/dashboard.html
  src/script/dailyResources.ts
Labels: 🐞 BugFix

#59 ✨ feat: bookmark 페이지 내 컬렉션을 활용한 필터링 기능 구현
  src/pages/bookmark.html
  src/script/bookmarkRendering.ts
  src/script/collectionRendering.ts
  src/service/bookmark.ts
  src/types/bookmark.type.ts
Labels: 🔨 Refactor, ✨ Feature, 🎨 Html&css, ✅ Done

#60 Release/v1.0.0/hyunsoo
  index.html
  public/favicon.svg
  src/components/DailyResources/daily-resources.ts
  src/components/GithubCard/githubCard.ts
  src/components/Modal/modal.html
  src/components/Sidebar/Sidebar.ts
  src/components/Sidebar/sidebar.ts
  src/main.ts
  src/pages/bookmark.html
  src/pages/dashboard.html
  src/pages/login.html
  src/pages/resource.html
  src/pages/sample.html
  src/script/bookmarkRendering.ts
  src/script/collectionModal.ts
  src/script/collectionRendering.ts
  src/script/dailyResources.ts
  src/script/filter.ts
  src/script/header.ts
  src/script/login.ts
  src/script/modalRendering.ts
  src/script/resourceRendering.ts
  src/types/resource.type.ts
Labels: 🔨 Refactor, 🌏 Deploy, ✅ Done

#61 main 브랜치에 v1.0.0 배포
  index.html
  public/favicon.svg
  src/components/DailyResources/daily-resources.html
  src/components/DailyResources/daily-resources.ts
  src/components/GithubCard/github-card.html
  src/components/GithubCard/githubCard.ts
  src/components/Modal/modal.html
  src/components/Sidebar/Sidebar.ts
  src/components/Sidebar/sidebar.ts
  src/data/resource.json
  src/main.ts
  src/pages/bookmark.html
  src/pages/dashboard.html
  src/pages/login.html
  src/pages/resource.html
  src/pages/sample.html
  src/script/bookmarkRendering.ts
  src/script/collectionModal.ts
  src/script/collectionRendering.ts
  src/script/dailyResources.ts
  src/script/filter.ts
  src/script/header.ts
  src/script/login.ts
  src/script/modalRendering.ts
  src/script/resourceRendering.ts
  src/service/bookmark.ts
  src/types/bookmark.type.ts
  src/types/filter.type.ts
  src/types/resource.type.ts
Labels: 🌏 Deploy

#62 ✨ feat: 카테고리 필터링 데이터 추가
  src/pages/resource.html
Labels: ✨ Feature

#63 Feature/collection/youngjune
  src/script/collectionRendering.ts
Labels: 🐞 BugFix, ✨ Feature, ✅ Done

#64 Feature/fix/hyunsoo
  index.html
  public/google9a2bc52a17bfbbc6.html
  public/img/apple-touch-icon-120x120.png
  public/img/apple-touch-icon-152x152.png
  public/img/apple-touch-icon-167x167.png
  public/img/apple-touch-icon-180x180.png
  public/img/og-image.png
  src/components/Sidebar/sidebar.ts
  src/pages/bookmark.html
  src/pages/login.html
  src/pages/resource.html
  src/script/header.ts
Labels: 🐞 BugFix, ✅ Done

#65 v.1.0.2 배포
  index.html
  public/google9a2bc52a17bfbbc6.html
  public/img/apple-touch-icon-120x120.png
  public/img/apple-touch-icon-152x152.png
  public/img/apple-touch-icon-167x167.png
  public/img/apple-touch-icon-180x180.png
  public/img/og-image.png
  src/components/Sidebar/sidebar.ts
  src/pages/bookmark.html
  src/pages/login.html
  src/pages/resource.html
  src/script/collectionRendering.ts
  src/script/header.ts
Labels: 🌏 Deploy

#68 v.1.0.2 버그 수정
  src/components/Sidebar/sidebar.ts
Labels: 🌏 Deploy

#69 🐛 bugfix: 간격 조절 및 반응형 UI 수정
  index.html
  src/components/Modal/modal.html
  src/pages/resource.html
Labels: 🐞 BugFix, ✨ Feature

#70 🐛 bugfix: 컬렉션 선택시 버튼 기능 미동작 오류 해결
  src/script/bookmarkRendering.ts
  src/script/collectionRendering.ts
Labels: 🐞 BugFix, 🔨 Refactor, ✅ Done

#71 💄 style: 설명 텍스트 추가 및 스타일 통일
  index.html
  src/pages/bookmark.html
  src/pages/resource.html
  src/script/resourceRendering.ts
Labels: 🎨 Html&css, ✅ Done

#75 🐛 bugfix: 북마크 링크 이벤트 수정
  src/components/Sidebar/sidebar.ts
  src/script/bookmarkRendering.ts
Labels: 🐞 BugFix

#74 ✨ feat: 리소스 페이지 option, value 추가
  src/pages/resource.html
  src/style.css
Labels: ✨ Feature

#76 💄 style: 모달창 레이아웃 UI 통일
  index.html
  src/pages/resource.html
  src/script/collectionModal.ts
Labels: 🎨 Html&css, ✅ Done

#78 🔧 fix: 사이드바 레이아웃 수정
  index.html
  src/pages/bookmark.html
  src/pages/login.html
  src/pages/resource.html
Labels: 🐞 BugFix, 🎨 Html&css, ✅ Done

#79 🐛 bugfix: 모달창 데이터 렌더링이 정상 작동되지 않은 건 해결
  src/script/modalRendering.ts
Labels: 🐞 BugFix, 🔨 Refactor, ✅ Done

#77 📝 Docs: Update README.md
  README.md
Labels: 📃 Docs

#80 ✨ feat: 리소스 데이터 추가
  src/data/resource.json
  src/pages/resource.html
Labels: ✅ Done

#81 v.1.0.3
  README.md
  index.html
  src/components/Modal/modal.html
  src/components/Sidebar/sidebar.ts
  src/data/resource.json
  src/pages/bookmark.html
  src/pages/login.html
  src/pages/resource.html
  src/script/bookmarkRendering.ts
  src/script/collectionModal.ts
  src/script/collectionRendering.ts
  src/script/modalRendering.ts
  src/script/resourceRendering.ts
  src/style.css
Labels: 🌏 Deploy

#82 🐛 bugfix: 모달 스크롤바 숨김 처리 오류 수정
  index.html
  src/pages/resource.html
  src/script/modalRendering.ts
Labels: 🐞 BugFix

#83 📝 Docs: README.md 업데이트
  README.md
Labels: 📃 Docs
